version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bookstore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:2.10
    container_name: bookstore-nats
    ports:
      - "4222:4222"

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: bookstore
    ports:
      - "50051:50051"

  book-service:
    build:
      context: ./book-service
    container_name: book-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: bookstore
    ports:
      - "50052:50052"

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    depends_on:
      - postgres
      - user-service
      - book-service
      - nats
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: bookstore
    ports:
      - "50053:50053"

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    depends_on:
      - nats

volumes:
  postgres_data:
